[package]
name = "radix_tree_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["packed"]
packed = ["bitflags"]

[dependencies]
bitflags = { version = "1.3.2", optional = true }
